// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
//IMPORTS///////////////////////////////////////////////////////////////////////
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

//CLASSES///////////////////////////////////////////////////////////////////////
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) { //determine which platform the user is using
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        return macos;

      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzGRVBvRWA2PBDRT8yvGdKQ3GFiDPKdQI',
    appId: '1:339853541909:web:e4ec0f6524dff72a7bc41c',
    messagingSenderId: '339853541909',
    projectId: 'mercersafe',
    authDomain: 'mercersafe.firebaseapp.com',
    databaseURL: 'https://mercersafe-default-rtdb.firebaseio.com',
    storageBucket: 'mercersafe.appspot.com',
    measurementId: 'G-VX07TD56ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5hknvNNFWToM0sC7eXzq2MIJcpV2RWR8',
    appId: '1:339853541909:android:038137f638c93acf7bc41c',
    messagingSenderId: '339853541909',
    projectId: 'mercersafe',
    databaseURL: 'https://mercersafe-default-rtdb.firebaseio.com',
    storageBucket: 'mercersafe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfBvvbeHic92RIf2AOVX6DdAG0QOYn27w',
    appId: '1:339853541909:ios:4b851f9c2318d5887bc41c',
    messagingSenderId: '339853541909',
    projectId: 'mercersafe',
    databaseURL: 'https://mercersafe-default-rtdb.firebaseio.com',
    storageBucket: 'mercersafe.appspot.com',
    iosClientId: '339853541909-oo2nhktutjk77kkufo6lvjph4ddu3upq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfBvvbeHic92RIf2AOVX6DdAG0QOYn27w',
    appId: '1:339853541909:ios:4b851f9c2318d5887bc41c',
    messagingSenderId: '339853541909',
    projectId: 'mercersafe',
    databaseURL: 'https://mercersafe-default-rtdb.firebaseio.com',
    storageBucket: 'mercersafe.appspot.com',
    iosClientId: '339853541909-oo2nhktutjk77kkufo6lvjph4ddu3upq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
//END OF firebase_options.dart//////////////////////////////////////////////////
